// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "df4984dc-4ba6-4506-9b2e-4928fa0bbfd2";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onLedSwitchChange();
void onBedChange();
void onServoControlChange();
void onServoAngleChange();

CloudAngle angle;
CloudLight led_switch;
CloudSwitch bed;
CloudTelevision servoControl;
CloudTemperatureSensor temprature;
int ldr;
int servoAngle;
CloudRelativeHumidity humidity;
bool airQuality;
bool piezo;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(angle, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(led_switch, READWRITE, ON_CHANGE, onLedSwitchChange, 1);
  ArduinoCloud.addProperty(bed, READWRITE, ON_CHANGE, onBedChange);
  ArduinoCloud.addProperty(servoControl, READWRITE, ON_CHANGE, onServoControlChange);
  ArduinoCloud.addProperty(temprature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(ldr, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(servoAngle, READWRITE, ON_CHANGE, onServoAngleChange);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(airQuality, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(piezo, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
